#!/usr/bin/env python3
# Hey Emacs, this is -*-python-*-

# swish2pdf: translate a CSV report from Swish into PDFs

import sys
import os
import argparse
import csv
import re
import time
from itertools import groupby

import fpdf

excel_escape_re = re.compile('^="(.*)"$')

pdf_fields = {
    'sv': (('datum', 'Datum:'),
           ('tid', 'Tid:'),
           ('referensnummer', 'Referensnummer:'),
           ('belopp', 'Belopp:'),
           ('mobilnummer', 'Mobilnummer:'),
           ('namn', 'Namn:'),
           ('meddelande', 'Meddelande:'))
}

parser = argparse.ArgumentParser(description = 'Translate Swish CSV report into PDFs')
parser.add_argument('-o', '--output-dir', default = '.',
                    help = 'Output directory for the files, default is current directory.')
parser.add_argument('-e', '--encoding', default = 'iso-8859-1',
                    help = 'Input file text encoding, default iso-8859-1.')
parser.add_argument('input_files', metavar = 'CSV', nargs = '*',
                    help = 'Files to process. If none are provided, stdin is read.')

def main():
    args = parser.parse_args()

    if args.input_files:
        input_files = [open(fname, mode = 'rt', newline = '', encoding = args.encoding)
                       for fname in args.input_files]
    else:
        input_files = [sys.stdin]

    for f in input_files:
        translate_csv(csv.reader(f, delimiter = ';', skipinitialspace = True), args.output_dir)

def translate_csv(csv_input, output_dir):
    def keyfunc(v):
        return v['_accounting_date']

    rows = sorted(read_csv(csv_input), key=keyfunc)
    for date, payments in groupby(rows, key=keyfunc):
        generate_pdf(date, payments, output_dir)


def read_csv(csv_input):
    header = None
    for row in csv_input:
        # Skip rows with too few columns, those are report metadata
        if len(row) > 8:
            if header is None:
                header = [h.lower() for h in row]
            else:
                values = {}
                for i, field in enumerate(header):
                    if field:
                        values[field] = strip_escape(row[i])

                accounting_date = values['datum']
                date = time.strptime(accounting_date, '%Y-%m-%d')
                hour = int(values['tid'].split(':')[0])

                # Accounting cutoff seems to be 21:00
                if hour >= 21:
                    t = time.mktime(date) + (24 * 3600)
                    accounting_date = time.strftime('%Y-%m-%d', time.localtime(t))

                values['_accounting_date'] = accounting_date
                yield values


def strip_escape(data):
    """Remove any ="xyz" Excel style escaping."""
    m = excel_escape_re.match(data)
    if m:
        return m.group(1)
    else:
        return data



def generate_pdf(date, payments, output_dir, language = 'sv'):
    pdf = fpdf.FPDF('P', 'mm', 'A4')

    for values in payments:
        pdf.add_page()
        pdf.set_font('Arial', 'B', 18)
        pdf.cell(0, 10, 'Swishbetalning', align= 'C', border = 'B')
        pdf.ln()

        for field, description in pdf_fields[language]:
            pdf.set_font('Arial', 'B', 14)
            pdf.cell(60, 10, description)
            pdf.set_font('Arial', '', 14)
            pdf.multi_cell(0, 8, values[field])

    # In Python3 fpdf 1.7.2 can only output latin-1

    filename = 'swish_{}.pdf'.format(values['_accounting_date'])
    path = os.path.join(output_dir, filename)
    with open(path, 'wt', encoding = 'latin-1') as f:
        print('wrote {}'.format(path))
        f.write(pdf.output(dest = 'S'))


if __name__ == '__main__':
    main()
